version: '2'
services:
  registry:
    restart: always
    image: registry:2
    container_name: "registry"
#    ports:
#      -5000:5000
    volumes:
      - registry:/var/lib/registry
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.registry.frontend.rule=Host:registry.kenevist.ir"
      - "traefik.registry.port=5000"
      - "traefik.registry.protocol=http"
    networks:
      - web
networks:
  web:
    external: true
