debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]
                    
[entryPoints]                  
  [entryPoints.http]           
  address = ":80"              
    [entryPoints.http.redirect]
    entryPoint = "https"
                     
  [entryPoints.https]
  address = ":443"
 
[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "kenevist.ir"
watch = true
exposedByDefault = false

[acme]
email = "kenevist@gmail.com"
storage = "/letsencrypt/acme.json"
entryPoint = "https"
[acme.tlsChallenge]


