logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]
                    
[entryPoints]                  
  [entryPoints.http]           
  address = ":80"              
    [entryPoints.http.redirect]
    entryPoint = "https"
                     
  [entryPoints.https]
  address = ":443"
 
[frontends]       
  [frontends.www]            
    backend = "kenevist"
      [frontends.www.routes.a]
      rule = "Host:www.kenevist.ir,www.kenevist.com,kenevist.ir,kenevist.com"

  [frontends.wwwChat]            
    backend = "kenevistChat"
      [frontends.wwwChat.routes.a]
      rule = "Host:www.kenevist.ir,www.kenevist.com,kenevist.ir,kenevist.com;Path:/longpolling"
 

  [frontends.git]
    backend = "gitlab"
      [frontends.git.routes.a]
      rule = "Host:git.kenevist.ir,git.kenevist.com"
                      
                      
  [frontends.registry]  
    backend = "registry"
      [frontends.registry.routes.a]
      rule = "Host:registry.kenevist.ir,registry.kenevist.com"

[backends]
  [backends.kenevist]
    [backends.kenevist.servers.odin]
    url="http://10.10.0.1:8069"

  [backends.kenevistChat]
    [backends.kenevistChat.servers.odin]
    url="http://10.10.0.1:8071"

  [backends.gitlab]
    [backends.gitlab.servers.freya]
    url="http://10.10.0.10:80"

  [backends.registry]
    [backends.registry.servers.freya]
    url="http://10.10.0.10:5000"

[acme]
email = "kenevist@gmail.com"
storage = "/letsencrypt/acme.json"
entryPoint = "https"
[acme.tlsChallenge]

