version: '2'

services:
  redis:
    restart: always
    image: redis:alpine
    command:
      - --loglevel warning
    volumes:
      - redis:/data
    networks:
      - backend

networks:
  backend:
    external: true

volumes:
  redis:
